const WORDS = [
  {"noun":"Auge","article":"das","plural":null,"en":"Eye","note":null,"pluralArticleDiffers":null},
  {"noun":"Auto","article":"das","plural":null,"en":"Car","note":null,"pluralArticleDiffers":null},
  {"noun":"Bahnticket","article":"das","plural":null,"en":"Train Ticket","note":null,"pluralArticleDiffers":null},
  {"noun":"Bein","article":"das","plural":null,"en":"Leg","note":null,"pluralArticleDiffers":null},
  {"noun":"Bett","article":"das","plural":null,"en":"Bed","note":null,"pluralArticleDiffers":null},
  {"noun":"Bier","article":"das","plural":null,"en":"Beer","note":null,"pluralArticleDiffers":null},
  {"noun":"Bild","article":"das","plural":null,"en":"Picture","note":null,"pluralArticleDiffers":null},
  {"noun":"Boot","article":"das","plural":null,"en":"The Boat","note":null,"pluralArticleDiffers":null},
  {"noun":"Brot","article":"das","plural":null,"en":"Bread","note":null,"pluralArticleDiffers":null},
  {"noun":"Brötchen","article":"das","plural":null,"en":"Bread Roll","note":null,"pluralArticleDiffers":null},
  {"noun":"Bücherregal","article":"das","plural":null,"en":"The Bookshelf","note":null,"pluralArticleDiffers":null},
  {"noun":"Café","article":"das","plural":null,"en":"Café","note":null,"pluralArticleDiffers":null},
  {"noun":"Datum","article":"das","plural":null,"en":"Date","note":null,"pluralArticleDiffers":null},
  {"noun":"Ei","article":"das","plural":null,"en":"Egg","note":null,"pluralArticleDiffers":null},
  {"noun":"Flugticket","article":"das","plural":null,"en":"Flight Ticket","note":null,"pluralArticleDiffers":null},
  {"noun":"Geld","article":"das","plural":null,"en":"Money","note":null,"pluralArticleDiffers":null},
  {"noun":"Gleis","article":"das","plural":null,"en":"Track","note":null,"pluralArticleDiffers":null},
  {"noun":"Haar","article":"das","plural":"Haare","en":"Hair","note":"The plural (Haare) takes 'die' — that's the plural marker every German noun gets, not a sign of gender. The singular is das Haar.","pluralArticleDiffers":true},
  {"noun":"Haltesignal","article":"das","plural":null,"en":"Stop Signal","note":null,"pluralArticleDiffers":null},
  {"noun":"Handy","article":"das","plural":null,"en":"Cell Phone","note":null,"pluralArticleDiffers":null},
  {"noun":"Hemd","article":"das","plural":null,"en":"Shirt","note":null,"pluralArticleDiffers":null},
  {"noun":"Hotel","article":"das","plural":null,"en":"Hotel","note":null,"pluralArticleDiffers":null},
  {"noun":"Hühnerfleisch","article":"das","plural":null,"en":"Chicken","note":null,"pluralArticleDiffers":null},
  {"noun":"Jahr","article":"das","plural":null,"en":"Year","note":null,"pluralArticleDiffers":null},
  {"noun":"Kind","article":"das","plural":"Kinder","en":"Child","note":"The plural (Kinder) takes 'die' — that's the plural marker every German noun gets, not a sign of gender. The singular is das Kind.","pluralArticleDiffers":true},
  {"noun":"Kino","article":"das","plural":null,"en":"Cinema","note":null,"pluralArticleDiffers":null},
  {"noun":"Kleid","article":"das","plural":null,"en":"Dress","note":null,"pluralArticleDiffers":null},
  {"noun":"Knie","article":"das","plural":null,"en":"Knee","note":null,"pluralArticleDiffers":null},
  {"noun":"Kopfkissen","article":"das","plural":null,"en":"Pillow","note":null,"pluralArticleDiffers":null},
  {"noun":"Kunstmuseum","article":"das","plural":null,"en":"Art Museum","note":null,"pluralArticleDiffers":null},
  {"noun":"Lehrbuch","article":"das","plural":null,"en":"Textbook","note":null,"pluralArticleDiffers":null},
  {"noun":"Medikament","article":"das","plural":null,"en":"Medication","note":null,"pluralArticleDiffers":null},
  {"noun":"Motorrad","article":"das","plural":null,"en":"Motorcycle","note":null,"pluralArticleDiffers":null},
  {"noun":"Ohr","article":"das","plural":null,"en":"Ear","note":null,"pluralArticleDiffers":null},
  {"noun":"Ohropax","article":"das","plural":null,"en":"Earplugs","note":null,"pluralArticleDiffers":null},
  {"noun":"Problem","article":"das","plural":null,"en":"Problem","note":null,"pluralArticleDiffers":null},
  {"noun":"Restaurant","article":"das","plural":null,"en":"Restaurant","note":null,"pluralArticleDiffers":null},
  {"noun":"Rindfleisch","article":"das","plural":null,"en":"Beef","note":null,"pluralArticleDiffers":null},
  {"noun":"Sauerkraut","article":"das","plural":null,"en":"Sauerkraut","note":null,"pluralArticleDiffers":null},
  {"noun":"Schiff","article":"das","plural":null,"en":"Ship","note":null,"pluralArticleDiffers":null},
  {"noun":"Sicherheitspersonal","article":"das","plural":null,"en":"Security Personnel","note":null,"pluralArticleDiffers":null},
  {"noun":"Sofa","article":"das","plural":null,"en":"Sofa","note":null,"pluralArticleDiffers":null},
  {"noun":"Studio","article":"das","plural":null,"en":"Studio","note":null,"pluralArticleDiffers":null},
  {"noun":"Stück","article":"das","plural":null,"en":"Piece","note":null,"pluralArticleDiffers":null},
  {"noun":"T-Shirt","article":"das","plural":null,"en":"T-Shirt","note":null,"pluralArticleDiffers":null},
  {"noun":"Tablet","article":"das","plural":null,"en":"Tablet","note":null,"pluralArticleDiffers":null},
  {"noun":"Telefon","article":"das","plural":null,"en":"Telephone","note":null,"pluralArticleDiffers":null},
  {"noun":"Verkehrsschild","article":"das","plural":null,"en":"Traffic Sign","note":null,"pluralArticleDiffers":null},
  {"noun":"Waschbecken","article":"das","plural":null,"en":"The Sink/Wash Basin","note":null,"pluralArticleDiffers":null},
  {"noun":"Wasser","article":"das","plural":null,"en":"Water","note":null,"pluralArticleDiffers":null},
  {"noun":"Wetter","article":"das","plural":null,"en":"Weather","note":null,"pluralArticleDiffers":null},
  {"noun":"Wohneigentum","article":"das","plural":null,"en":"Home Ownership","note":null,"pluralArticleDiffers":null},
  {"noun":"Wörterbuch","article":"das","plural":null,"en":"Dictionary","note":null,"pluralArticleDiffers":null},
  {"noun":"Zimmer","article":"das","plural":null,"en":"Room (in a house or hotel)","note":null,"pluralArticleDiffers":null},
  {"noun":"Öl","article":"das","plural":null,"en":"Oil","note":null,"pluralArticleDiffers":null},
  {"noun":"Anzug","article":"der","plural":null,"en":"Suit","note":null,"pluralArticleDiffers":null},
  {"noun":"Apfel","article":"der","plural":null,"en":"Apple","note":null,"pluralArticleDiffers":null},
  {"noun":"Architekt","article":"der","plural":null,"en":"Architect","note":null,"pluralArticleDiffers":null},
  {"noun":"Arzt","article":"der","plural":null,"en":"Doctor","note":null,"pluralArticleDiffers":null},
  {"noun":"Assistent","article":"der","plural":null,"en":"Assistant","note":null,"pluralArticleDiffers":null},
  {"noun":"Autofahrer","article":"der","plural":null,"en":"Driver","note":null,"pluralArticleDiffers":null},
  {"noun":"Bahnhof","article":"der","plural":null,"en":"Train Station","note":null,"pluralArticleDiffers":null},
  {"noun":"Bauch","article":"der","plural":null,"en":"Belly","note":null,"pluralArticleDiffers":null},
  {"noun":"Bikini","article":"der","plural":null,"en":"Bikini","note":null,"pluralArticleDiffers":null},
  {"noun":"Bildschirm","article":"der","plural":null,"en":"Screen","note":null,"pluralArticleDiffers":null},
  {"noun":"Bruder","article":"der","plural":null,"en":"Brother","note":null,"pluralArticleDiffers":null},
  {"noun":"Bus","article":"der","plural":null,"en":"Bus","note":null,"pluralArticleDiffers":null},
  {"noun":"Check-in-Schalter","article":"der","plural":null,"en":"Check-in Counter","note":null,"pluralArticleDiffers":null},
  {"noun":"Computer","article":"der","plural":null,"en":"Computer","note":null,"pluralArticleDiffers":null},
  {"noun":"Drucker","article":"der","plural":null,"en":"Printer","note":null,"pluralArticleDiffers":null},
  {"noun":"Eigentümer","article":"der","plural":null,"en":"Owner","note":null,"pluralArticleDiffers":null},
  {"noun":"Espresso","article":"der","plural":null,"en":"Espresso","note":null,"pluralArticleDiffers":null},
  {"noun":"Esstisch","article":"der","plural":null,"en":"Dining Table","note":null,"pluralArticleDiffers":null},
  {"noun":"Fahrgast","article":"der","plural":null,"en":"Passenger (bus/train)","note":null,"pluralArticleDiffers":null},
  {"noun":"Fahrkartenautomat","article":"der","plural":null,"en":"Ticket Machine","note":null,"pluralArticleDiffers":null},
  {"noun":"Fahrkartenschalter","article":"der","plural":null,"en":"Ticket Counter","note":null,"pluralArticleDiffers":null},
  {"noun":"Fahrkartenverkäufer","article":"der","plural":null,"en":"Ticket Seller","note":null,"pluralArticleDiffers":null},
  {"noun":"Fahrplan","article":"der","plural":null,"en":"Timetable","note":null,"pluralArticleDiffers":null},
  {"noun":"Fernseher","article":"der","plural":null,"en":"TV","note":null,"pluralArticleDiffers":null},
  {"noun":"Finger","article":"der","plural":null,"en":"Finger","note":null,"pluralArticleDiffers":null},
  {"noun":"Flughafen","article":"der","plural":null,"en":"Airport","note":null,"pluralArticleDiffers":null},
  {"noun":"Flugplan","article":"der","plural":null,"en":"Flight Plan","note":null,"pluralArticleDiffers":null},
  {"noun":"Flugsteig","article":"der","plural":null,"en":"Departure Gate","note":null,"pluralArticleDiffers":null},
  {"noun":"Fotoapparat","article":"der","plural":null,"en":"Camera","note":null,"pluralArticleDiffers":null},
  {"noun":"Freund","article":"der","plural":null,"en":"Friend","note":null,"pluralArticleDiffers":null},
  {"noun":"Fuß","article":"der","plural":null,"en":"Foot","note":null,"pluralArticleDiffers":null},
  {"noun":"Fußball","article":"der","plural":null,"en":"Football","note":null,"pluralArticleDiffers":null},
  {"noun":"Führerschein","article":"der","plural":null,"en":"Driver's License","note":null,"pluralArticleDiffers":null},
  {"noun":"Geschirrspüler","article":"der","plural":null,"en":"Dishwasher","note":null,"pluralArticleDiffers":null},
  {"noun":"Großraumwagen","article":"der","plural":null,"en":"Open-plan railway carriage","note":null,"pluralArticleDiffers":null},
  {"noun":"Hafen","article":"der","plural":null,"en":"Harbor","note":null,"pluralArticleDiffers":null},
  {"noun":"Hals","article":"der","plural":null,"en":"Neck","note":null,"pluralArticleDiffers":null},
  {"noun":"Hut","article":"der","plural":null,"en":"Hat","note":"A brimmed hat.","pluralArticleDiffers":null},
  {"noun":"Hörsaal","article":"der","plural":null,"en":"Lecture Hall","note":null,"pluralArticleDiffers":null},
  {"noun":"Informatiker","article":"der","plural":null,"en":"IT Specialist","note":null,"pluralArticleDiffers":null},
  {"noun":"Informationsschalter","article":"der","plural":null,"en":"Information Desk","note":null,"pluralArticleDiffers":null},
  {"noun":"Ingenieur","article":"der","plural":null,"en":"Engineer","note":null,"pluralArticleDiffers":null},
  {"noun":"Joghurt","article":"der","plural":null,"en":"Yogurt","note":null,"pluralArticleDiffers":null},
  {"noun":"Kaffee","article":"der","plural":null,"en":"Coffee","note":null,"pluralArticleDiffers":null},
  {"noun":"Kalender","article":"der","plural":null,"en":"Calendar","note":null,"pluralArticleDiffers":null},
  {"noun":"Kellner","article":"der","plural":null,"en":"Waiter","note":null,"pluralArticleDiffers":null},
  {"noun":"Kleiderschrank","article":"der","plural":null,"en":"Clothing Closet","note":null,"pluralArticleDiffers":null},
  {"noun":"Koffer","article":"der","plural":null,"en":"Suitcase","note":null,"pluralArticleDiffers":null},
  {"noun":"Kopf","article":"der","plural":null,"en":"Head","note":null,"pluralArticleDiffers":null},
  {"noun":"Kuchen","article":"der","plural":null,"en":"Cake","note":null,"pluralArticleDiffers":null},
  {"noun":"Käse","article":"der","plural":null,"en":"Cheese","note":null,"pluralArticleDiffers":null},
  {"noun":"Körper","article":"der","plural":null,"en":"Body","note":null,"pluralArticleDiffers":null},
  {"noun":"Küchenschrank","article":"der","plural":null,"en":"Kitchen Cabinet","note":null,"pluralArticleDiffers":null},
  {"noun":"Kühlschrank","article":"der","plural":null,"en":"Refrigerator","note":null,"pluralArticleDiffers":null},
  {"noun":"Künstler","article":"der","plural":null,"en":"Artist","note":null,"pluralArticleDiffers":null},
  {"noun":"Lachs","article":"der","plural":null,"en":"Salmon","note":null,"pluralArticleDiffers":null},
  {"noun":"Laptop","article":"der","plural":null,"en":"Laptop","note":null,"pluralArticleDiffers":null},
  {"noun":"Lehrer","article":"der","plural":null,"en":"Teacher","note":null,"pluralArticleDiffers":null},
  {"noun":"Lesesaal","article":"der","plural":null,"en":"Reading Room","note":null,"pluralArticleDiffers":null},
  {"noun":"Lippenstift","article":"der","plural":null,"en":"Lipstick","note":null,"pluralArticleDiffers":null},
  {"noun":"Löffel","article":"der","plural":null,"en":"Spoon","note":null,"pluralArticleDiffers":null},
  {"noun":"Mann","article":"der","plural":null,"en":"Husband","note":null,"pluralArticleDiffers":null},
  {"noun":"Mantel","article":"der","plural":null,"en":"Coat","note":null,"pluralArticleDiffers":null},
  {"noun":"Mieter","article":"der","plural":null,"en":"Tenant","note":null,"pluralArticleDiffers":null},
  {"noun":"Monat","article":"der","plural":"Monate","en":"Month","note":"The plural (Monate) takes 'die' — that's the plural marker every German noun gets, not a sign of gender. The singular is der Monat.","pluralArticleDiffers":true},
  {"noun":"Mund","article":"der","plural":null,"en":"Mouth","note":null,"pluralArticleDiffers":null},
  {"noun":"Onkel","article":"der","plural":null,"en":"Uncle","note":null,"pluralArticleDiffers":null},
  {"noun":"Parkplatz","article":"der","plural":null,"en":"Parking Lot","note":null,"pluralArticleDiffers":null},
  {"noun":"Partner","article":"der","plural":null,"en":"Partner","note":null,"pluralArticleDiffers":null},
  {"noun":"Passagier","article":"der","plural":null,"en":"Passenger (plane/ship)","note":null,"pluralArticleDiffers":null},
  {"noun":"Pfeffer","article":"der","plural":null,"en":"Pepper","note":null,"pluralArticleDiffers":null},
  {"noun":"Pullover","article":"der","plural":null,"en":"Sweater","note":null,"pluralArticleDiffers":null},
  {"noun":"Quadratmeter","article":"der","plural":null,"en":"Square Meter","note":null,"pluralArticleDiffers":null},
  {"noun":"Quark","article":"der","plural":null,"en":"Quark (type of cheese)","note":null,"pluralArticleDiffers":null},
  {"noun":"Raum","article":"der","plural":null,"en":"Room / space (generic)","note":null,"pluralArticleDiffers":null},
  {"noun":"Regenschirm","article":"der","plural":null,"en":"Umbrella","note":null,"pluralArticleDiffers":null},
  {"noun":"Reis","article":"der","plural":null,"en":"Rice","note":null,"pluralArticleDiffers":null},
  {"noun":"Reisepass","article":"der","plural":null,"en":"Passport","note":null,"pluralArticleDiffers":null},
  {"noun":"Rock","article":"der","plural":null,"en":"Skirt","note":null,"pluralArticleDiffers":null},
  {"noun":"Rucksack","article":"der","plural":null,"en":"Backpack","note":null,"pluralArticleDiffers":null},
  {"noun":"Rücken","article":"der","plural":null,"en":"Back","note":null,"pluralArticleDiffers":null},
  {"noun":"Saft","article":"der","plural":null,"en":"Juice","note":null,"pluralArticleDiffers":null},
  {"noun":"Salat","article":"der","plural":null,"en":"Salad","note":null,"pluralArticleDiffers":null},
  {"noun":"Schal","article":"der","plural":null,"en":"Scarf","note":null,"pluralArticleDiffers":null},
  {"noun":"Schinken","article":"der","plural":null,"en":"Ham","note":null,"pluralArticleDiffers":null},
  {"noun":"Schlüssel","article":"der","plural":null,"en":"Key","note":null,"pluralArticleDiffers":null},
  {"noun":"Schmerz","article":"der","plural":"Schmerzen","en":"Pain","note":"The plural (Schmerzen) takes 'die' — that's the plural marker every German noun gets, not a sign of gender. The singular is der Schmerz.","pluralArticleDiffers":true},
  {"noun":"Schrank","article":"der","plural":null,"en":"Closet","note":null,"pluralArticleDiffers":null},
  {"noun":"Schreibtisch","article":"der","plural":null,"en":"Desk","note":null,"pluralArticleDiffers":null},
  {"noun":"Schuh","article":"der","plural":"Schuhe","en":"Shoe","note":"The plural (Schuhe) takes 'die' — that's the plural marker every German noun gets, not a sign of gender. The singular is der Schuh.","pluralArticleDiffers":true},
  {"noun":"Schuhschrank","article":"der","plural":null,"en":"Shoe Closet","note":null,"pluralArticleDiffers":null},
  {"noun":"Seminarraum","article":"der","plural":null,"en":"Seminar Room","note":null,"pluralArticleDiffers":null},
  {"noun":"Sessel","article":"der","plural":null,"en":"Armchair","note":null,"pluralArticleDiffers":null},
  {"noun":"Singlehaushalt","article":"der","plural":null,"en":"Single Household","note":null,"pluralArticleDiffers":null},
  {"noun":"Sitzplatz","article":"der","plural":null,"en":"Seat","note":null,"pluralArticleDiffers":null},
  {"noun":"Sohn","article":"der","plural":null,"en":"Son","note":null,"pluralArticleDiffers":null},
  {"noun":"Spiegel","article":"der","plural":null,"en":"Mirror","note":null,"pluralArticleDiffers":null},
  {"noun":"Sportschuh","article":"der","plural":"Sportschuhe","en":"Sports shoe","note":"The plural (Sportschuhe) takes 'die' — that's the plural marker every German noun gets, not a sign of gender. The singular is der Sportschuh.","pluralArticleDiffers":true},
  {"noun":"Stift","article":"der","plural":null,"en":"Pen","note":null,"pluralArticleDiffers":null},
  {"noun":"Student","article":"der","plural":null,"en":"Student","note":null,"pluralArticleDiffers":null},
  {"noun":"Stuhl","article":"der","plural":null,"en":"Chair","note":null,"pluralArticleDiffers":null},
  {"noun":"Supermarkt","article":"der","plural":null,"en":"Supermarket","note":null,"pluralArticleDiffers":null},
  {"noun":"Tag","article":"der","plural":null,"en":"Day","note":null,"pluralArticleDiffers":null},
  {"noun":"Tee","article":"der","plural":null,"en":"Tea","note":null,"pluralArticleDiffers":null},
  {"noun":"Teller","article":"der","plural":null,"en":"Plate","note":null,"pluralArticleDiffers":null},
  {"noun":"Teppich","article":"der","plural":null,"en":"Carpet","note":null,"pluralArticleDiffers":null},
  {"noun":"Termin","article":"der","plural":null,"en":"Appointment","note":null,"pluralArticleDiffers":null},
  {"noun":"Tisch","article":"der","plural":null,"en":"Table","note":null,"pluralArticleDiffers":null},
  {"noun":"Topf","article":"der","plural":null,"en":"Pot","note":null,"pluralArticleDiffers":null},
  {"noun":"Vater","article":"der","plural":null,"en":"Father","note":null,"pluralArticleDiffers":null},
  {"noun":"Wein","article":"der","plural":null,"en":"Wine","note":null,"pluralArticleDiffers":null},
  {"noun":"Zahn","article":"der","plural":null,"en":"Tooth","note":null,"pluralArticleDiffers":null},
  {"noun":"Zug","article":"der","plural":null,"en":"Train","note":"Refers to a specific train.","pluralArticleDiffers":null},
  {"noun":"linke Arm","article":"der","plural":null,"en":"Left Arm","note":null,"pluralArticleDiffers":null},
  {"noun":"rechte Arm","article":"der","plural":null,"en":"Right Arm","note":null,"pluralArticleDiffers":null},
  {"noun":"Abfahrt","article":"die","plural":null,"en":"Departure","note":null,"pluralArticleDiffers":null},
  {"noun":"Ampel","article":"die","plural":null,"en":"Traffic Light","note":null,"pluralArticleDiffers":null},
  {"noun":"Ananas","article":"die","plural":null,"en":"Pineapple","note":null,"pluralArticleDiffers":null},
  {"noun":"Ankunftshalle","article":"die","plural":null,"en":"Arrival Hall","note":null,"pluralArticleDiffers":null},
  {"noun":"Apotheke","article":"die","plural":null,"en":"Pharmacy","note":null,"pluralArticleDiffers":null},
  {"noun":"Atmosphäre","article":"die","plural":null,"en":"Atmosphere","note":null,"pluralArticleDiffers":null},
  {"noun":"Autobahn","article":"die","plural":null,"en":"Highway","note":null,"pluralArticleDiffers":null},
  {"noun":"Badehose","article":"die","plural":null,"en":"Swimsuit","note":null,"pluralArticleDiffers":null},
  {"noun":"Badewanne","article":"die","plural":null,"en":"Bathtub","note":null,"pluralArticleDiffers":null},
  {"noun":"Bahn","article":"die","plural":null,"en":"Railway / train (system)","note":null,"pluralArticleDiffers":null},
  {"noun":"Banane","article":"die","plural":null,"en":"Banana","note":null,"pluralArticleDiffers":null},
  {"noun":"Bank","article":"die","plural":null,"en":"Bank","note":null,"pluralArticleDiffers":null},
  {"noun":"Birne","article":"die","plural":null,"en":"Pear","note":null,"pluralArticleDiffers":null},
  {"noun":"Brille","article":"die","plural":null,"en":"Glasses","note":null,"pluralArticleDiffers":null},
  {"noun":"Butter","article":"die","plural":null,"en":"Butter","note":null,"pluralArticleDiffers":null},
  {"noun":"Cafeteria","article":"die","plural":null,"en":"Cafeteria / snack bar","note":null,"pluralArticleDiffers":null},
  {"noun":"Cola","article":"die","plural":null,"en":"Cola","note":null,"pluralArticleDiffers":null},
  {"noun":"Couch","article":"die","plural":null,"en":"Couch","note":null,"pluralArticleDiffers":null},
  {"noun":"Currywurst","article":"die","plural":null,"en":"Currywurst","note":null,"pluralArticleDiffers":null},
  {"noun":"Eigentumswohnung","article":"die","plural":null,"en":"Condominium","note":null,"pluralArticleDiffers":null},
  {"noun":"Eltern","article":"die","plural":null,"en":"Parents","note":"Plural-only noun — there is no singular \"das Elter\" in everyday use.","pluralArticleDiffers":null},
  {"noun":"Erdbeere","article":"die","plural":null,"en":"Strawberry","note":null,"pluralArticleDiffers":null},
  {"noun":"Flasche","article":"die","plural":null,"en":"Bottle","note":null,"pluralArticleDiffers":null},
  {"noun":"Frau","article":"die","plural":null,"en":"Woman","note":null,"pluralArticleDiffers":null},
  {"noun":"Gabel","article":"die","plural":null,"en":"Fork","note":null,"pluralArticleDiffers":null},
  {"noun":"Garderobe","article":"die","plural":null,"en":"Wardrobe","note":null,"pluralArticleDiffers":null},
  {"noun":"Gurke","article":"die","plural":null,"en":"Cucumber","note":null,"pluralArticleDiffers":null},
  {"noun":"Hand","article":"die","plural":"Hände","en":"Hand","note":null,"pluralArticleDiffers":false},
  {"noun":"Hose","article":"die","plural":null,"en":"Pants","note":null,"pluralArticleDiffers":null},
  {"noun":"Jacke","article":"die","plural":null,"en":"Jacket","note":null,"pluralArticleDiffers":null},
  {"noun":"Jahreszeit","article":"die","plural":"Jahreszeiten","en":"Season","note":null,"pluralArticleDiffers":false},
  {"noun":"Kaffeemaschine","article":"die","plural":null,"en":"Coffee Machine","note":null,"pluralArticleDiffers":null},
  {"noun":"Karte","article":"die","plural":null,"en":"Card / map","note":null,"pluralArticleDiffers":null},
  {"noun":"Kartoffel","article":"die","plural":null,"en":"Potato","note":null,"pluralArticleDiffers":null},
  {"noun":"Kreditkarte","article":"die","plural":null,"en":"Credit Card","note":null,"pluralArticleDiffers":null},
  {"noun":"Lampe","article":"die","plural":null,"en":"Lamp","note":null,"pluralArticleDiffers":null},
  {"noun":"Leberwurst","article":"die","plural":null,"en":"Liver Sausage","note":null,"pluralArticleDiffers":null},
  {"noun":"Limonade","article":"die","plural":null,"en":"Lemonade","note":null,"pluralArticleDiffers":null},
  {"noun":"Maschine","article":"die","plural":null,"en":"Machine","note":null,"pluralArticleDiffers":null},
  {"noun":"Mensa","article":"die","plural":null,"en":"Cafeteria (university canteen)","note":null,"pluralArticleDiffers":null},
  {"noun":"Mietwohnung","article":"die","plural":null,"en":"Rental Apartment","note":null,"pluralArticleDiffers":null},
  {"noun":"Milch","article":"die","plural":null,"en":"Milk","note":null,"pluralArticleDiffers":null},
  {"noun":"Minute","article":"die","plural":null,"en":"Minute","note":null,"pluralArticleDiffers":null},
  {"noun":"Mutter","article":"die","plural":null,"en":"Mother","note":null,"pluralArticleDiffers":null},
  {"noun":"Möglichkeit","article":"die","plural":"Möglichkeiten","en":"Possibility","note":null,"pluralArticleDiffers":false},
  {"noun":"Mütze","article":"die","plural":null,"en":"Cap / beanie","note":"A knit or soft cap, as opposed to der Hut (brimmed hat).","pluralArticleDiffers":null},
  {"noun":"Nacht","article":"die","plural":null,"en":"Night","note":null,"pluralArticleDiffers":null},
  {"noun":"Nase","article":"die","plural":null,"en":"Nose","note":null,"pluralArticleDiffers":null},
  {"noun":"Nudel","article":"die","plural":"Nudeln","en":"Noodle","note":null,"pluralArticleDiffers":false},
  {"noun":"Nummer","article":"die","plural":null,"en":"Number","note":null,"pluralArticleDiffers":null},
  {"noun":"Paprika","article":"die","plural":null,"en":"Capsicum","note":null,"pluralArticleDiffers":null},
  {"noun":"Passkontrolle","article":"die","plural":null,"en":"Passport Control","note":null,"pluralArticleDiffers":null},
  {"noun":"Pfanne","article":"die","plural":null,"en":"Pan","note":null,"pluralArticleDiffers":null},
  {"noun":"Regenjacke","article":"die","plural":null,"en":"Raincoat","note":null,"pluralArticleDiffers":null},
  {"noun":"S-Bahn","article":"die","plural":null,"en":"Suburban train (S-Bahn)","note":null,"pluralArticleDiffers":null},
  {"noun":"Sahne","article":"die","plural":null,"en":"Cream","note":null,"pluralArticleDiffers":null},
  {"noun":"Schokolade","article":"die","plural":null,"en":"Chocolate","note":null,"pluralArticleDiffers":null},
  {"noun":"Schwester","article":"die","plural":null,"en":"Sister","note":null,"pluralArticleDiffers":null},
  {"noun":"Seite","article":"die","plural":null,"en":"Page","note":null,"pluralArticleDiffers":null},
  {"noun":"Sekunde","article":"die","plural":null,"en":"Second","note":null,"pluralArticleDiffers":null},
  {"noun":"Socke","article":"die","plural":"Socken","en":"Sock","note":null,"pluralArticleDiffers":false},
  {"noun":"Sonnenbrille","article":"die","plural":null,"en":"Sunglasses","note":null,"pluralArticleDiffers":null},
  {"noun":"Sportskleidung","article":"die","plural":null,"en":"Sportswear","note":null,"pluralArticleDiffers":null},
  {"noun":"Straße","article":"die","plural":null,"en":"Street","note":null,"pluralArticleDiffers":null},
  {"noun":"Straßenbahn","article":"die","plural":null,"en":"Tram","note":null,"pluralArticleDiffers":null},
  {"noun":"Stunde","article":"die","plural":null,"en":"Hour","note":null,"pluralArticleDiffers":null},
  {"noun":"Suppe","article":"die","plural":null,"en":"Soup","note":null,"pluralArticleDiffers":null},
  {"noun":"Tablette","article":"die","plural":null,"en":"Pill / tablet (medicine)","note":"Not to be confused with das Tablet (the electronic device).","pluralArticleDiffers":null},
  {"noun":"Tankstelle","article":"die","plural":null,"en":"Gas Station","note":null,"pluralArticleDiffers":null},
  {"noun":"Tante","article":"die","plural":null,"en":"Aunt","note":null,"pluralArticleDiffers":null},
  {"noun":"Tasche","article":"die","plural":null,"en":"Bag","note":null,"pluralArticleDiffers":null},
  {"noun":"Tasse","article":"die","plural":null,"en":"Cup","note":null,"pluralArticleDiffers":null},
  {"noun":"Tochter","article":"die","plural":null,"en":"Daughter","note":null,"pluralArticleDiffers":null},
  {"noun":"Toilette","article":"die","plural":null,"en":"Toilet","note":null,"pluralArticleDiffers":null},
  {"noun":"Tomate","article":"die","plural":null,"en":"Tomato","note":null,"pluralArticleDiffers":null},
  {"noun":"Torte","article":"die","plural":null,"en":"Cake","note":null,"pluralArticleDiffers":null},
  {"noun":"Touristeninformation","article":"die","plural":null,"en":"Tourist Information","note":null,"pluralArticleDiffers":null},
  {"noun":"Tür","article":"die","plural":null,"en":"Door","note":null,"pluralArticleDiffers":null},
  {"noun":"U-Bahn","article":"die","plural":null,"en":"Subway / underground (U-Bahn)","note":null,"pluralArticleDiffers":null},
  {"noun":"Uhr","article":"die","plural":null,"en":"Clock","note":null,"pluralArticleDiffers":null},
  {"noun":"Unterwäsche","article":"die","plural":null,"en":"Underwear","note":null,"pluralArticleDiffers":null},
  {"noun":"Vase","article":"die","plural":null,"en":"Vase","note":null,"pluralArticleDiffers":null},
  {"noun":"Verbindung","article":"die","plural":null,"en":"Connection","note":null,"pluralArticleDiffers":null},
  {"noun":"Waschmaschine","article":"die","plural":null,"en":"Washing Machine","note":null,"pluralArticleDiffers":null},
  {"noun":"Wohngemeinschaft","article":"die","plural":null,"en":"Shared Apartment","note":null,"pluralArticleDiffers":null},
  {"noun":"Zehe","article":"die","plural":"Zehen","en":"Toe","note":null,"pluralArticleDiffers":false},
  {"noun":"Zeitschrift","article":"die","plural":null,"en":"Magazine","note":null,"pluralArticleDiffers":null},
  {"noun":"Zeitung","article":"die","plural":null,"en":"Newspaper","note":null,"pluralArticleDiffers":null},
  {"noun":"Zwiebel","article":"die","plural":null,"en":"Onion","note":null,"pluralArticleDiffers":null}
];